allow JSON rpc with array params
softwaregroup-bg/ut-front pull request #68
Opened 2017-09-19 14:52 UTC by wtfti

2017-09-19 18:54 UTC, zetxx requested changes
you should not make params passed muttable

2017-09-19 22:26 UTC, kalinkrustev requested changes
> you should not make params passed muttable

I agree with that. Better put some IF that checks if we have array and copy it. Also there is no point to have {} as non-first parameter in Object.assign

Also you need to assign the request to somebody, who will take care for merging. Otherwise looks you are only asking for review and not for merging.

2017-09-25 13:29 UTC, mitushy commented
Updated the PR.

* We are currently completely replacing the ```headers``` parameter if a corsCookie exists and they pass from the frontend unaltered otherwise. Maybe we should consider merging them instead?
* In the case of ```action.params``` being an array, we are attaching a ```headers``` property directly to that array instance.

2017-09-25 20:59 UTC, kalinkrustev commented
I am OK with the change, @zetxx please review and merge if you are ok too.

2017-09-26 13:36 UTC, zetxx requested changes

2017-09-26 13:36 UTC, zetxx commented on react/middleware.js
> +            const methodParams = cloneParams(action.params);
there is no need to make it constant if you change it later

2017-09-26 13:36 UTC, zetxx commented on react/middleware.js
> +                Object.assign(methodParams, { headers: { 'x-xsrf-token': corsCookie } });
you should do:
```js
methodParams = Object.assign(methodParams, { headers: { 'x-xsrf-token': corsCookie } });
```
in order to explicitly show that you overwrite `methodParams`'s value

2017-09-27 07:07 UTC, merged